<?php require_once __DIR__ . '/inc_app.php'; require_login(); if (!is_admin()) redirect('index.php');
if ($_SERVER['REQUEST_METHOD']==='POST') {
  if (isset($_POST['delete'])) execute_query('DELETE FROM users WHERE id=?', 'i', [(int)$_POST['id']]);
  if (isset($_POST['save'])) execute_query('UPDATE users SET name=?, role=?, phone=? WHERE id=?', 'sssi', [$_POST['name'], $_POST['role'], $_POST['phone'], (int)$_POST['id']]);
  if (isset($_POST['add'])) execute_query('INSERT INTO users (name,phone,role) VALUES (?,?,?)', 'sss', [$_POST['name'], $_POST['phone'], $_POST['role']]);
  redirect('admin-users.php');
}
$users = fetch_all('SELECT * FROM users ORDER BY id DESC'); ?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Пользователи</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><?php include 'admin_header.php'; ?><div class="container py-4"><h1>Пользователи</h1>
<form method="post" class="row g-2 mb-3"><input type="hidden" name="add" value="1"><div class="col"><input name="name" class="form-control" placeholder="Имя" required></div><div class="col"><input name="phone" class="form-control" placeholder="Телефон" required></div><div class="col"><select name="role" class="form-select"><option>client</option><option>artist</option><option>admin</option></select></div><div class="col-auto"><button class="btn btn-dark">Добавить</button></div></form>
<table class="table table-sm"><tr><th>ID</th><th>Имя</th><th>Телефон</th><th>Роль</th><th></th></tr><?php foreach($users as $u): ?><tr><form method="post"><td><?= (int)$u['id']; ?><input type="hidden" name="id" value="<?= (int)$u['id']; ?>"></td><td><input class="form-control form-control-sm" name="name" value="<?= h($u['name']); ?>"></td><td><input class="form-control form-control-sm" name="phone" value="<?= h($u['phone']); ?>"></td><td><select name="role" class="form-select form-select-sm"><option <?= $u['role']==='client'?'selected':''; ?>>client</option><option <?= $u['role']==='artist'?'selected':''; ?>>artist</option><option <?= $u['role']==='admin'?'selected':''; ?>>admin</option></select></td><td class="d-flex gap-1"><button class="btn btn-sm btn-outline-dark" name="save">Сохранить</button><button class="btn btn-sm btn-outline-danger" name="delete">Удалить</button></td></form></tr><?php endforeach; ?></table></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>
